import type { ReactNode } from 'react'
import { ArrowRight, BadgeCheck, BookOpen, ExternalLink, Search, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { Standard } from '../services/standards'

export function StatusBadge({ status }: { status: string }) { const styles: Record<string, string> = { Active: 'bg-emerald-50 text-emerald-700 border-emerald-200', Revised: 'bg-amber-50 text-amber-700 border-amber-200', Draft: 'bg-slate-100 text-slate-700 border-slate-200' }; return <span className={`inline-flex items-center gap-1 rounded-full border px-2.5 py-1 text-xs font-semibold ${styles[status] ?? styles.Draft}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{status}</span> }
export function SearchBar({ value, onChange, placeholder, actionLabel = 'Search', onAction }: { value: string; onChange: (value: string) => void; placeholder: string; actionLabel?: string; onAction?: () => void }) { return <div className="flex min-h-14 w-full items-center gap-2 rounded-2xl border border-slate-200 bg-white p-1.5 shadow-sm focus-within:border-blue-300 focus-within:ring-4 focus-within:ring-blue-50"><Search className="ml-3 shrink-0 text-slate-400" size={20} /><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="min-w-0 flex-1 bg-transparent px-1 text-sm text-slate-900 outline-none placeholder:text-slate-400 sm:text-base" /><button onClick={onAction} className="inline-flex h-11 shrink-0 items-center gap-2 rounded-xl bg-blue-600 px-4 text-sm font-semibold text-white transition hover:bg-blue-700"><span className="hidden sm:inline">{actionLabel}</span><ArrowRight size={17} /></button></div> }
export function StandardCard({ standard }: { standard: Standard }) { return <article className="lift rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-bold text-blue-700">{standard.code}</p><h3 className="mt-1 text-lg font-bold text-slate-900">{standard.title}</h3></div><StatusBadge status={standard.status} /></div><p className="mt-4 line-clamp-2 text-sm leading-6 text-slate-600"><span className="font-semibold text-slate-800">Scope:</span> {standard.scope}</p><div className="mt-5 flex flex-wrap items-center gap-2 text-xs font-medium text-slate-500"><span className="rounded-md bg-slate-100 px-2 py-1">{standard.category}</span><span>{standard.year}</span></div><div className="mt-5 flex gap-3 border-t border-slate-100 pt-4"><Link to={`/standards/${standard.id}`} className="inline-flex items-center gap-1.5 text-sm font-semibold text-blue-700 hover:text-blue-800">View standard <ArrowRight size={15} /></Link><Link to="/chat" className="text-sm font-semibold text-slate-600 hover:text-slate-900">Ask AI</Link></div></article> }
export function EvidenceCard({ clause = 'Clause 4.2', page = 'Page 12', compact = false }: { clause?: string; page?: string; compact?: boolean }) { return <article className={`rounded-2xl border border-blue-100 bg-blue-50/60 ${compact ? 'p-4' : 'p-5'}`}><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-sm font-bold text-blue-950"><ShieldCheck size={18} className="text-blue-600" /> Official evidence</div><span className="rounded-full bg-emerald-100 px-2 py-1 text-[11px] font-bold uppercase tracking-wide text-emerald-700">High confidence</span></div><p className="mt-3 text-sm leading-6 text-slate-700">This response references the prescribed quality, hygiene, treatment and labelling requirements for the product category.</p><div className="mt-4 flex flex-wrap gap-2 text-xs font-semibold text-blue-800"><span className="rounded-md border border-blue-200 bg-white px-2 py-1">BIS</span><span className="rounded-md border border-blue-200 bg-white px-2 py-1">{clause}</span><span className="rounded-md border border-blue-200 bg-white px-2 py-1">{page}</span></div></article> }
export function SectionHeading({ eyebrow, title, copy, action }: { eyebrow?: string; title: string; copy?: string; action?: ReactNode }) { return <div className="mb-7 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow && <p className="text-xs font-bold uppercase tracking-[.16em] text-blue-700">{eyebrow}</p>}<h2 className="mt-2 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">{title}</h2>{copy && <p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600 sm:text-base">{copy}</p>}</div>{action}</div> }
export function EmptyState({ title, copy }: { title: string; copy: string }) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><BookOpen className="mx-auto text-slate-300" size={32} /><h3 className="mt-4 font-bold text-slate-900">{title}</h3><p className="mx-auto mt-2 max-w-sm text-sm text-slate-500">{copy}</p></div> }
export function SourceLink({ children }: { children: ReactNode }) { return <button className="inline-flex items-center gap-1 text-sm font-semibold text-blue-700 hover:text-blue-900">{children}<ExternalLink size={14} /></button> }
export function OfficialMark() { return <span className="inline-flex items-center gap-1.5 text-xs font-semibold text-emerald-700"><BadgeCheck size={15} /> Official BIS source</span> }
